### ISSUE TITLE
Can't handle float32 pixel type

### ISSUE THREAD

**Issue by adamjtaylor** [jmuhlich/auto-minerva#1]
`story.py` fails for an example HTAN dataset (`syn25701060`, an IMC image)

```
python story.py ~/miniature/data/HT060P1_REMAIN_ROI_04.ome.tiff  > HT060P1_REMAIN_ROI04.story.json
```

```
opening image: /home/ubuntu/miniature/data/HT060P1_REMAIN_ROI_04.ome.tiff
Traceback (most recent call last):
  File "/home/ubuntu/auto-minerva/story.py", line 109, in <module>
    main()
  File "/home/ubuntu/auto-minerva/story.py", line 58, in main
    raise Exception(f"Can't handle {zarray.dtype} pixel type")
Exception: Can't handle float32 pixel type
```

**Comment by adamjtaylor** [comment]
I expect that the MS detection methods (IMC & MIBI) will have float pixel types due to the detector type.

**Comment by jmuhlich** [comment]
This will still need some changes in the minerva-author headless rendering script to support float pixels.
